apiVersion: v1
kind: Pod
metadata:
  name: nettestpriv
  namespace: podtest
spec:
  containers:
  - image: quay.io/jramsay/nettest
    imagePullPolicy: Always
    name: nettestlog
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
