allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: null
apiVersion: security.openshift.io/v1
defaultAddCapabilities: null
fsGroup:
  type: MustRunAs
groups:
- system:authenticated
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: Allows NET_ADMIN and NET_RAW capabilities (as well as running as root)
  name: allowsockopt
priority: null
readOnlyRootFilesystem: false
allowedCapabilities:
- NET_ADMIN
- NET_RAW
requiredDropCapabilities:
- KILL
- MKNOD
- SETUID
- SETGID
seccompProfiles: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users: []
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
