apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: process-exporter
  name: process-exporter
  namespace: openshift-monitoring
spec:
  endpoints:
  - interval: 15s
    port: metrics
    scheme: http
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      k8s-app: process-exporter
