apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: container-mount-namespace
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf8;base64,W1VuaXRdCkRlc2NyaXB0aW9uPU1hbmFnZXMgYSBtb3VudCBuYW1lc3BhY2UgdGhhdCBib3RoIGt1YmVsZXQgYW5kIGNyaW8gY2FuIHVzZSB0byBzaGFyZSB0aGVpciBjb250YWluZXItc3BlY2lmaWMgbW91bnRzCgpbU2VydmljZV0KVHlwZT1vbmVzaG90ClJlbWFpbkFmdGVyRXhpdD15ZXMKUnVudGltZURpcmVjdG9yeT1jb250YWluZXItbW91bnQtbmFtZXNwYWNlCkVudmlyb25tZW50PVJVTlRJTUVfRElSRUNUT1JZPSV0L2NvbnRhaW5lci1tb3VudC1uYW1lc3BhY2UKRW52aXJvbm1lbnQ9QklORF9QT0lOVD0ldC9jb250YWluZXItbW91bnQtbmFtZXNwYWNlL21udApFeGVjU3RhcnRQcmU9YmFzaCAtYyAiZmluZG1udCAke1JVTlRJTUVfRElSRUNUT1JZfSB8fCBtb3VudCAtLW1ha2UtdW5iaW5kYWJsZSAtLWJpbmQgJHtSVU5USU1FX0RJUkVDVE9SWX0gJHtSVU5USU1FX0RJUkVDVE9SWX0iCkV4ZWNTdGFydFByZT10b3VjaCAke0JJTkRfUE9JTlR9CkV4ZWNTdGFydD11bnNoYXJlIC0tbW91bnQ9JHtCSU5EX1BPSU5UfSAtLXByb3BhZ2F0aW9uIHNsYXZlCkV4ZWNTdG9wPXVtb3VudCAtUiAke1JVTlRJTUVfRElSRUNUT1JZfQo=
        filesystem: root
        mode: 420
        path: /etc/systemd/system/container-mount-namespace.service
      - contents:
          source: data:text/plain;charset=utf8;base64,W1VuaXRdCldhbnRzPWNvbnRhaW5lci1tb3VudC1uYW1lc3BhY2Uuc2VydmljZQpBZnRlcj1jb250YWluZXItbW91bnQtbmFtZXNwYWNlLnNlcnZpY2UKCltTZXJ2aWNlXQpFeGVjU3RhcnRQcmU9ZXh0cmFjdEV4ZWNTdGFydCAlbiAvJXQvJU4tZXhlY3N0YXJ0LmVudiBPUklHX0VYRUNTVEFSVApFbnZpcm9ubWVudEZpbGU9LS8ldC8lTi1leGVjc3RhcnQuZW52CkV4ZWNTdGFydD0KRXhlY1N0YXJ0PWJhc2ggLWMgIm5zZW50ZXIgLS1tb3VudD0ldC9jb250YWluZXItbW91bnQtbmFtZXNwYWNlL21udCBcCiAgICAke09SSUdfRVhFQ1NUQVJUfSIK
        filesystem: root
        mode: 420
        path: /etc/systemd/system/crio.service.d/20-container-mount-namespace.conf
      - contents:
          source: data:text/plain;charset=utf8;base64,W1VuaXRdCldhbnRzPWNvbnRhaW5lci1tb3VudC1uYW1lc3BhY2Uuc2VydmljZQpBZnRlcj1jb250YWluZXItbW91bnQtbmFtZXNwYWNlLnNlcnZpY2UKCltTZXJ2aWNlXQpFeGVjU3RhcnRQcmU9ZXh0cmFjdEV4ZWNTdGFydCAlbiAvJXQvJU4tZXhlY3N0YXJ0LmVudiBPUklHX0VYRUNTVEFSVApFbnZpcm9ubWVudEZpbGU9LS8ldC8lTi1leGVjc3RhcnQuZW52CkV4ZWNTdGFydD0KRXhlY1N0YXJ0PWJhc2ggLWMgIm5zZW50ZXIgLS1tb3VudD0ldC9jb250YWluZXItbW91bnQtbmFtZXNwYWNlL21udCBcCiAgICAke09SSUdfRVhFQ1NUQVJUfSIK
        filesystem: root
        mode: 420
        path: /etc/systemd/system/kubelet.service.d/20-container-mount-namespace.conf
      - contents:
          source: data:text/plain;charset=utf8;base64,IyEvYmluL2Jhc2gKCmRlYnVnKCkgewogIGVjaG8gJEAgPiYyCn0KCnVzYWdlKCkgewogIGVjaG8gVXNhZ2U6ICQoYmFzZW5hbWUgJDApIFVOSVQgW2VudmZpbGUgW3Zhcm5hbWVdXQogIGVjaG8KICBlY2hvIEV4dHJhY3QgdGhlIGNvbnRlbnRzIG9mIHRoZSBmaXJzdCBFeGVjU3RhcnQgc3RhbnphIGZyb20gdGhlIGdpdmVuIHN5c3RlbWQgdW5pdCBhbmQgcmV0dXJuIGl0IHRvIHN0ZG91dAogIGVjaG8KICBlY2hvICJJZiAnZW52ZmlsZScgaXMgcHJvdmlkZWQsIHB1dCBpdCBpbiB0aGVyZSBpbnN0ZWFkLCBhcyBhbiBlbnZpcm9ubWVudCB2YXJpYWJsZSBuYW1lZCAndmFybmFtZSciCiAgZWNobyAiRGVmYXVsdCAndmFybmFtZScgaXMgRVhFQ1NUQVJUIGlmIG5vdCBzcGVjaWZpZWQiCiAgZXhpdCAxCn0KClVOSVQ9JDEKRU5WRklMRT0kMgpWQVJOQU1FPSQzCmlmIFtbIC16ICRVTklUIHx8ICRVTklUID09ICItLWhlbHAiIHx8ICRVTklUID09ICItaCIgXV07IHRoZW4KICB1c2FnZQpmaQpkZWJ1ZyAiRXh0cmFjdGluZyBFeGVjU3RhcnQgZnJvbSAkVU5JVCIKRklMRT0kKHN5c3RlbWN0bCBjYXQgJFVOSVQgfCBoZWFkIC1uIDEpCkZJTEU9JHtGSUxFI1wjIH0KaWYgW1sgISAtZiAkRklMRSBdXTsgdGhlbgogIGRlYnVnICJGYWlsZWQgdG8gZmluZCByb290IGZpbGUgZm9yIHVuaXQgJFVOSVQgKCRGSUxFKSIKICBleGl0CmZpCmRlYnVnICJTZXJ2aWNlIGRlZmluaXRpb24gaXMgaW4gJEZJTEUiCkVYRUNTVEFSVD0kKHNlZCAtbiAtZSAnL15FeGVjU3RhcnQ9LipcXCQvLC9bXlxcXSQvIHsgcy9eRXhlY1N0YXJ0PS8vOyBwIH0nIC1lICcvXkV4ZWNTdGFydD0uKlteXFxdJC8geyBzL15FeGVjU3RhcnQ9Ly87IHAgfScgJEZJTEUpCgppZiBbWyAkRU5WRklMRSBdXTsgdGhlbgogIFZBUk5BTUU9JHtWQVJOQU1FOi1FWEVDU1RBUlR9CiAgZWNobyAiJHtWQVJOQU1FfT0ke0VYRUNTVEFSVH0iID4gJEVOVkZJTEUKZWxzZQogIGVjaG8gJEVYRUNTVEFSVApmaQo=
        filesystem: root
        mode: 493
        path: /usr/local/bin/extractExecStart
      - contents:
          source: data:text/plain;charset=utf8;base64,IyEvYmluL2Jhc2gKbnNlbnRlciAtLW1vdW50PS9ydW4vY29udGFpbmVyLW1vdW50LW5hbWVzcGFjZS9tbnQgIiRAIgo=
        filesystem: root
        mode: 493
        path: /usr/local/bin/nsenterCms
